markdown: kramdown
pygments: false
author: niean
name: "田园木竹"

safe: true
permalink: /:year/:month/:day/:title
url: http://blog.niean.name
paginate: 16

comments:
  provider: duoshuo
  duoshuo:
    short_name: nieanan
